### ISSUE TITLE
Python 3 tag

### ISSUE THREAD

**Issue by SimonKrughoff** [esheldon/esutil#17]
@esheldon We are currently migrating the LSST stack to support Python 3.  Since this is currently a third party dependency, we are very interested in having a tagged version that runs under Python 3.  Is that in the short term plan?  Is there anything I can do to help that happening?

**Comment by esheldon** [comment]
This is not a problem, I'll tag a new version soon.

**Comment by SimonKrughoff** [comment]
Excellent, thanks!

**Comment by esheldon** [comment]
v0.6.0 is released, via a tag on github or via pip
