### ISSUE TITLE
esutil assumes that on Darwin Python was built with both `i386` and `x86_64`

### ISSUE THREAD

**Issue by wmwv** [esheldon/esutil#18]
`esutil` assumes that on Darwin (Mac OS X) Python was built with both `i386` and `x86_64` but this isn't necessarily true.  

The `setup.py` file has the following

```
if platform.system()=='Darwin':
    extra_compile_args=['-arch','i386','-arch','x86_64']
    extra_link_args=['-arch','i386','-arch','x86_64']
else:
    extra_compile_args=[]
    extra_link_args=[]
```

But, e.g., on my system, Python was only installed with x86_64 libraries.

**Comment by timj** [comment]
I think a quick check of the relevant entry in `distutils.sysconfig` would work, only add `x86_64` and `i386` if that string appears in the build options.

**Comment by esheldon** [comment]
Thanks for the report.  Can you verify that works for you? If so can you please send  a pull request?

**Comment by timj** [comment]
@wmwv does something like this work for you:
```python
#!/usr/bin/env python

import distutils.sysconfig

cflags = distutils.sysconfig.get_config_var("PY_CFLAGS")

architectures = ("x86_64", "i386")
extra_compile_args = []
for arch in architectures:
    if "arch {}".format(arch) in cflags:
        extra_compile_args.extend(["-arch", arch])

extra_link_args = extra_compile_args
print("Args: {}".format(extra_compile_args))
```
(obviously that's a standalone version). For me it just selects `x86_64` architecture on my Anaconda python and on my system python (made by apple) it includes both architectures. On my homebrew python it includes nothing because homebrew did not specify an architecture at all.

**Comment by timj** [comment]
Note that this version doesn't require the Darwin check.

**Comment by r-owen** [comment]
@timj is it a problem if the test does not detect any architecture (e.g. for homebrew)? Should there be a fallback value for that case?

**Comment by timj** [comment]
I don't understand why the architectures are specified at all as the default is usually the correct answer. If a python was configured to build extension libraries without any architecture specified I would assume that nothing should be specified by the user. If an architecture was specified you don't want to add extra values. Maybe removing all this code will "Just Work" now and it was there for ppc back in the day.

**Comment by wmwv** [comment]
@timj 
Yes, the snippet you provided above works and generates the correct architecture specifications (and non-specifications) on my Desktop and Laptop machines:

Laptop  (System and Fink):
```
[Calm tmp] /usr/bin/python test_esutil_patch_arch.py
Args: ['-arch', 'x86_64', '-arch', 'i386']
[Calm tmp] /sw/bin/python test_esutil_patch_arch.py
Args: []
```

Desktop (System and Homebrew):
```
[serenity tmp] /usr/bin/python test_esutil_patch_arch.py
Args: ['-arch', 'x86_64', '-arch', 'i386']
[serenity tmp] /usr/local/bin/python test_esutil_patch_arch.py
Args: []
```

where `test_esutil_patch_arch.py` is a file containing your snippet above.

**Comment by timj** [comment]
Can you convert this code into a pull request (assuming it fixes your problem) so @esheldon can see if it works for them?

**Comment by esheldon** [comment]
can we close this?  You can now conda install esutil

**Comment by timj** [comment]
It seems like setup.py no longer has the code in question so it seems to be solved.
