### ISSUE TITLE
Cannot import esutil

### ISSUE THREAD

**Issue by SheaYang** [esheldon/esutil#19]
Hi there, I successfully installed esutil, and when I tried to import the package, it gives me this error: 
`ImportError: /home/tao/anaconda2/lib/python2.7/site-packages/esutil/recfile/_records.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE`

Any idea how to fix this? Thanks!

**Comment by esheldon** [comment]
It is hard to tell from this report, but my guess is that this is some mismatch between the compiler or libraries used when compiling and when running python.
