### ISSUE TITLE
small bug/typo in wcsutil.py (too minor for a pull request)

### ISSUE THREAD

**Issue by terben** [esheldon/esutil#23]
There is a small bug/typo in the file `wcsutil.py`, line 597:

It currently is:
```
x,y = self._findxy_one(lon, lat, xtol=tol)
```
but it must read:
```
x,y = self._findxy_one(lon, lat, xtol=xtol)
```
(`tol` -> `xtol` at the end of the line)

**Comment by esheldon** [comment]
thanks very much, fixed in master
