### ISSUE TITLE
Please specify and include license

### ISSUE THREAD

**Issue by lupinix** [esheldon/esutil#25]
Hi,

I'd like to package esutil for Fedora, therefore I need information on the licensing of the package. Can you specify the license and add a copy to the source tree? Thanks :)

Greetings,
Christian

**Comment by beckermr** [comment]
Bump on this @esheldon. A license is needed for conda-forge as well.

**Comment by esheldon** [comment]
the license was specified in classifiers but not included. I added a LICENSE file

**Comment by beckermr** [comment]
This issue can be closed! Thanks @esheldon!
