### ISSUE TITLE
hdfs ls or du

### ISSUE THREAD

**Issue by mgentile-bit** [esheldon/esutil#62]
Using hdfs ls or du command i receive this error message:

a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "xxxxxxxxxxx/esutil/hdfs.py", line 139, in du
    lines = stdo.split("\n")
TypeError: a bytes-like object is required, not 'str'

**Comment by mgentile-bit** [comment]
A fix should be:
lines = stdo.split(b"\n")

**Comment by esheldon** [comment]
thanks for the report.  Would you like to submit a pull request?
