### ISSUE TITLE
`-std=c++11` breaks `clang` builds

### ISSUE THREAD

**Issue by jobovy** [esheldon/esutil#78]
The fix from #75 breaks the build process on Macs with clang (the default compiler), because clang doesn't allow the `-std=c++11` flag when compiling C code. So ideally, you'd only want to have this flag on for the `*.cpp` files, but not for the `*.c` files. However, this seems quite difficult to do, as `distutils` tries hard to use the same flags for all files. The easiest solution might just be to make this an optional flag that can be turned off or detecting that this flag doesn't work and turning it off automatically. Note that the current way of checking the compiler flags doesn't detect this issue, because it compiles a C++ file and for that the flag is fine. You could do the check with a C file, but I'm not sure that that doesn't lead to other issues.

**Comment by beckermr** [comment]
See this diff for a potential fix:

```
--- setup.py.orig	2023-01-08 06:55:28
+++ setup.py	2023-01-08 06:55:49
@@ -123,7 +123,8 @@
     cflags = extra_compile_args
     lflags = extra_link_args
 
-    cflags += ["-std=c++11"]
+    if platform.system() != "Darwin":
+        cflags += ["-std=c++11"]
 
     if platform.system() == "Darwin":
         # Usually Macs need this, but they might not, so try it, and only add
```

**Comment by jobovy** [comment]
I don’t think this will work, because you need the `-std=c++11` flag with clang too, just only for the C compiler.

**Comment by jobovy** [comment]
Or maybe you don't need the flag currently, although eventually you might need it. It's been a while since I opened this issue and haven't checked recently.

**Comment by beckermr** [comment]
The builds on conda-forge worked just fine.

**Comment by beckermr** [comment]
the default in clang is past c++11 now

**Comment by MacDaddy1660B** [comment]
Confirmed: commenting line `#cflags += ["-std=c++11"]` on `Darwin` systems results in a successful build.

**Comment by esheldon** [comment]
where are we on this?

**Comment by jobovy** [comment]
I can take a look and see whether I can fix this quickly. Still having the issue locally...
