### ISSUE TITLE
esutil pip install fails on github actions using ubuntu-latest (22.04)

### ISSUE THREAD

**Issue by erykoff** [esheldon/esutil#80]
I use pip in my github actions for redmapper.  And the esutil installation failed today, apparently caused by the update of `ubuntu-latest` from 20.04 to 22.04 in November/December (it was a rolling release).  Specifically requesting `ubuntu-20.04` fixed the issue (temporarily).

The pip install error was the following:
```
      esutil/htm/htmc.h:111:47: error: ISO C++17 does not allow dynamic exception specifications
        111 |                         const char* filename) throw (const char *);
            |                                               ^~~~~
```
Which is strange because it should be explicitly setting c++11, but I noticed that the build line looks like:
```
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/numpy/core/include -Iesutil/include -Iesutil/recfile -Iesutil/htm -Iesutil/htm/htm_src -I/opt/hostedtoolcache/Python/3.8.15/x64/include/python3.8 -c esutil/htm/htm_src/SpatialInterface.cpp -o build/temp.linux-x86_64-3.8/esutil/htm/htm_src/SpatialInterface.o
```
(That is, no use of the `-std=c++11` which should be there.)

**Comment by esheldon** [comment]
thanks for this

**Comment by jobovy** [comment]
I think the issue is that @erykoff is `pip` installing the latest release, which doesn't include #75, so doesn't set `-std=c++11`. You could just try adding it to `CFLAGS`, that should work.

**Comment by jobovy** [comment]
Also, the reason that this bug occurred when GHA switched to Ubuntu 22.04 is that the default GCC version changed to 11, which uses the C++17 standard by default:
* actions/runner-images#5490
* https://www.phoronix.com/news/GCC-11-Cpp-17-Default

**Comment by esheldon** [comment]
I tagged a new version and pushed to pypi

**Comment by esheldon** [comment]
is this working now?
