### ISSUE TITLE
Reverse indices are not properly sorted (and can change from version to version)

### ISSUE THREAD

**Issue by erykoff** [esheldon/esutil#87]
The following code snippet (a) doesn't return sorted indices and (b) results in different ordering from numpy 1.24 to numpy 1.26 on x86 processors.

```
import numpy as np
import esutil


arr = np.zeros(1000, dtype=np.int64)
arr[500: ] = 1

h, rev = esutil.stat.histogram(arr, rev=True)

print(rev[rev[0]: rev[1]])
print(rev[rev[1]: rev[2]])
```

The fix is that the histogram call to `argsort` should use `kind="stable"` which properly preserves sort order.

I don't want to fix this yet to allow my code to properly prepare for the different (but correct!) ordering.

**Comment by esheldon** [comment]
The docs say the underlying implementation will depend on data type, so we should make sure we get good coverage in the unit tests

**Comment by esheldon** [comment]
@erykoff are you ready for a fix for this?

**Comment by erykoff** [comment]
I haven't done anything about this because I didn't want to deal with writing the tests.  😞

**Comment by esheldon** [comment]
I'm happy to have the change when you are ready

**Comment by esheldon** [comment]
I think this was addressed by a recent PR
